[package]
name = "rust_qtile_helper"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.24", features = ["full"] }
winit = "0.28.7"
vulkano = "0.34.0"
vulkano-win = "0.34.0"

