[package]
name = "rust_qtile_helper"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
winit = "0.27"           # Use v0.27 so vulkano-win and our code agree
vulkano = "0.35"
vulkano-win = "0.34"
