[package]
name = "xcb_wm_bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
x11rb = "0.12.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-util = "0.7"
