[commands]
# Navigation (Focus) – corresponds to:
#   mod+h -> lazy.layout.left()
#   mod+l -> lazy.layout.right()
#   mod+j -> lazy.layout.down()
#   mod+k -> lazy.layout.up()
#   mod+space -> lazy.layout.next()
focus_left  = "move_focus -x -1"
focus_right = "move_focus -x 1"
focus_down  = "move_focus -y 1"
focus_up    = "move_focus -y -1"
focus_next  = "move_focus next"

# Window manipulation (Shuffle) – corresponds to:
#   mod+shift+h -> lazy.layout.shuffle_left()
#   mod+shift+l -> lazy.layout.shuffle_right()
#   mod+shift+j -> lazy.layout.shuffle_down()
#   mod+shift+k -> lazy.layout.shuffle_up()
shuffle_left  = "shuffle_left"
shuffle_right = "shuffle_right"
shuffle_down  = "shuffle_down"
shuffle_up    = "shuffle_up"

# Window resizing (Grow) – corresponds to:
#   mod+control+h -> lazy.layout.grow_left()
#   mod+control+l -> lazy.layout.grow_right()
#   mod+control+j -> lazy.layout.grow_down()
#   mod+control+k -> lazy.layout.grow_up()
grow_left  = "grow_left"
grow_right = "grow_right"
grow_down  = "grow_down"
grow_up    = "grow_up"

# Layout control & window management – corresponds to:
#   mod+shift+Return -> lazy.layout.toggle_split()
#   mod+Tab -> lazy.next_layout()
#   mod+f -> lazy.window.toggle_fullscreen()
#   mod+t -> lazy.window.toggle_floating()
#   mod+c -> lazy.window.kill()
toggle_split     = "toggle_split"
next_layout      = "next_layout"
kill_window      = "close_window"
toggle_fullscreen = "toggle_fullscreen"
toggle_floating   = "toggle_floating"
normalize        = "normalize"   # (if you implement a normalization command)

# System commands – corresponds to:
#   mod+control+r -> lazy.reload_config()
#   mod+control+q -> lazy.shutdown()
reload_config = "reload_config"
shutdown      = "shutdown"

# Applications – corresponds to:
#   mod+Return -> lazy.spawn(terminal) where terminal is "alacritty"
#   mod+p -> lazy.spawn("rofi -show drun")
spawn_terminal = "spawn alacritty"
spawn_rofi     = "spawn rofi -show drun"
